#!/usr/bin/env bash
set -u
. "$(dirname "$0")/testlib.sh"

method="$REPO_DIR/shared/method.md"
claude="$REPO_DIR/claude/SKILL.md"
codex="$REPO_DIR/codex/SKILL.md"
template="$REPO_DIR/assets/goal.md.tmpl"

assert_file_contains "$method" 'Triage|TRIAGE' 'canonical shared method documents triage'
assert_file_contains "$method" 'investigat' 'canonical shared method documents investigation'
assert_file_contains "$method" 'MUST-ASK|DERIVE' 'canonical shared method documents fact classification'
assert_file_contains "$method" 'gate' 'canonical shared method documents gates'
assert_file_contains "$method" 'chain' 'canonical shared method documents chaining'
assert_file_contains "$method" 'autonom' 'canonical shared method documents autonomy'
assert_file_contains "$method" 'success.*failure.*iteration.*cost.*wall-clock|success.*failure.*iterations.*cost.*wall-clock' 'canonical method requires complete stop rules'
assert_file_contains "$method" 'out-of-repository path alone is not protection|out-of-repository.*alone.*not' 'canonical method conditions gate-state resistance on sandbox permissions'
assert_file_contains "$method" 'GATE_SURFACE' 'canonical method requires explicit GATE_SURFACE configuration'
assert_file_contains "$method" 'whitespace-separated.*glob/list|glob/list.*whitespace-separated' 'canonical method documents GATE_SURFACE list semantics'
assert_file_contains "$method" 'repository root' 'canonical method documents repository-relative surface resolution'
assert_file_contains "$method" 'regular file' 'canonical method requires regular-file surface entries'
assert_file_contains "$method" 'surface digest detects only changes' 'canonical method limits digest protection to post-baseline changes'
assert_file_contains "$method" 'after its first trusted baseline' 'canonical method requires a trusted digest baseline'
assert_file_contains "$method" 'prime it before maker edits|read-only.*maker|pre-record.*baseline' 'canonical method requires protected or pre-established surface baseline'
assert_file_contains "$claude" 'shared/method.md' 'Claude adapter mandates the canonical shared method'
assert_file_contains "$codex" 'shared/method.md' 'Codex adapter mandates the canonical shared method'
assert_file_contains "$claude" '4,?000' 'Claude adapter documents the official 4,000-character condition limit'
assert_file_contains "$claude" 'stop_hook_active' 'Claude adapter documents stop_hook_active'
assert_file_contains "$claude" 'eight consecutive|8 consecutive' 'Claude adapter documents the eight-consecutive-block limit'
assert_file_contains "$claude" 'By default.*eight consecutive blocks without progress|By default.*8 consecutive blocks without progress' 'Claude adapter states the default no-progress block condition'
assert_file_contains "$claude" 'CLAUDE_CODE_STOP_HOOK_BLOCK_CAP' 'Claude adapter names the platform block-cap override'
assert_file_contains "$claude" 'GOAL_GATE_CAP.*<= 8|GOAL_GATE_CAP.*at least the chosen repository cap' 'Claude adapter keeps repository and platform caps compatible'
assert_file_contains "$codex" 'PreToolUse' 'Codex adapter documents PreToolUse coverage'
assert_file_contains "$codex" 'Bash' 'Codex adapter names Bash PreToolUse coverage'
assert_file_contains "$codex" 'apply_patch' 'Codex adapter names apply_patch PreToolUse coverage'
assert_file_contains "$codex" 'MCP' 'Codex adapter names MCP PreToolUse coverage'
assert_file_contains "$codex" 'local function' 'Codex adapter names other local-function PreToolUse coverage'
assert_file_contains "$codex" 'Hosted tools.*excluded|Hosted tools.*No' 'Codex adapter documents hosted-tool exceptions'
assert_file_contains "$codex" 'write_stdin.*not' 'Codex adapter documents write_stdin exception'
assert_file_contains "$claude" 'https://code.claude.com/docs/' 'Claude platform facts cite official documentation'
assert_file_contains "$codex" 'https://learn.chatgpt.com/docs/hooks' 'Codex platform facts cite official documentation'
assert_not_contains "$(cat "$codex")" '/goal[[:space:]]+complete' 'Codex adapter makes no unsupported /goal completion claim'
assert_not_contains "$(cat "$REPO_DIR/shared/autonomy.md")" 'Codex caveat:.*shell only|PreToolUse.*intercepts.*shell only' 'shared autonomy policy has no stale Codex shell-only claim'
shared_policy="$(cat "$REPO_DIR"/shared/*.md)"
assert_not_contains "$shared_policy" '`/goal|claude -p|codex exec|--dangerously-skip-permissions|CLAUDE_CODE_|stop_hook_active|#47810|transcript-only|transcript evaluator|Claude Code' 'shared policy contains no known platform-specific invocation or mechanics'

assert_file_contains "$template" 'stop_rules:' 'persisted sub-goal template has stop_rules'
assert_file_contains "$template" 'success' 'persisted sub-goal template has a success stop rule'
assert_file_contains "$template" 'failure' 'persisted sub-goal template has a failure stop rule'
assert_file_contains "$template" 'iteration' 'persisted sub-goal template has an iteration stop rule'
assert_file_contains "$template" 'cost' 'persisted sub-goal template has a cost stop rule'
assert_file_contains "$template" 'wall.?clock|time' 'persisted sub-goal template has a wall-clock stop rule'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'Class 3' 'autonomy policy names Class 3 actions'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'explicit.*bounded.*human|human.*bounded.*authori' 'Class 3 external or spending actions require bounded human authority'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'Class 4' 'autonomy policy names Class 4 actions'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'unattended' 'Class 4 policy is scoped to unattended execution'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'commit.*authori|authori.*commit' 'commits require user or repository authority'
assert_file_contains "$REPO_DIR/shared/chaining.md" 'insufficient' 'disjoint artifacts are explicitly insufficient for parallelism'

for gate in "$REPO_DIR/assets/gate.claude.sh" "$REPO_DIR/assets/gate.codex.sh"; do
  assert_not_contains "$(cat "$gate")" 'GATE_CMD:-pytest' 'gate has no stale implicit pytest command default'
  assert_file_contains "$gate" 'GATE_CMD' 'gate names explicit GATE_CMD configuration'
  assert_file_contains "$gate" 'GOAL_GATE_CAP' 'gate names explicit GOAL_GATE_CAP configuration'
done
assert_file_contains "$REPO_DIR/shared/gates.md" 'GATE_SURFACE' 'gate guide names mandatory GATE_SURFACE configuration'
assert_file_contains "$REPO_DIR/shared/gates.md" 'ordinary shell word splitting.*glob expansion|shell glob/list' 'gate guide documents exact surface expansion semantics'
assert_file_contains "$REPO_DIR/shared/gates.md" 'trusted baseline' 'gate guide warns that surface hashing needs a trusted baseline'
assert_file_contains "$REPO_DIR/shared/gates.md" 'read-only.*before' 'gate guide requires a protected surface before maker work'
assert_file_contains "$REPO_DIR/shared/gates.md" 'same session payload|same session-keyed state' 'gate guide limits trusted priming to the actual session key'
assert_file_contains "$REPO_DIR/shared/gates.md" '[Mm]anual or pre-session priming is not' 'gate guide rejects unreliable out-of-session priming'

assert_file_contains "$REPO_DIR/README.md" 'development install|live symlink' 'README explains live symlink development installs'
assert_file_contains "$REPO_DIR/README.md" '--force' 'README documents default refusal and --force'
assert_file_contains "$REPO_DIR/README.md" 'jq' 'README documents jq prerequisite'
assert_file_contains "$REPO_DIR/README.md" 'GATE_CMD' 'README documents trusted GATE_CMD'
assert_file_contains "$REPO_DIR/README.md" 'GOAL_GATE_CAP' 'README documents explicit gate cap'
assert_file_contains "$REPO_DIR/README.md" 'GATE_SURFACE' 'README documents mandatory gate surface'
assert_file_contains "$REPO_DIR/README.md" 'trusted baseline' 'README explains the trusted surface baseline'
assert_file_contains "$REPO_DIR/README.md" 'read-only.*before' 'README gives an operationally safe surface setup'
assert_file_contains "$REPO_DIR/README.md" 'same session payload.*state key' 'README explains the session-keyed priming constraint'
assert_file_contains "$REPO_DIR/README.md" 'manual or pre-session.*not reliable' 'README rejects unreliable priming guidance'
assert_file_contains "$REPO_DIR/README.md" 'decision.*block' 'README documents retry hook output'
assert_file_contains "$REPO_DIR/README.md" 'continue.*false|needs-human|needs human' 'README documents terminal gate output'
assert_file_contains "$REPO_DIR/README.md" '\.claude/settings\.json' 'README shows Claude hook registration'
assert_file_contains "$REPO_DIR/README.md" '\.codex/hooks\.json' 'README shows Codex hook registration'
assert_file_contains "$REPO_DIR/README.md" 'bash tests/run.sh' 'README names the contract test command'
assert_file_contains "$REPO_DIR/README.md" 'out of scope' 'README says an external driver is out of scope'
assert_file_contains "$REPO_DIR/PLAN.md" 'as-built|As-built' 'PLAN is an as-built record'
assert_file_contains "$REPO_DIR/PLAN.md" 'compatibility' 'PLAN contains a compatibility record'
assert_not_contains "$(cat "$REPO_DIR/PLAN.md")" 'Status:.*draft|Ready for your review before build' 'PLAN does not describe the implemented system as a draft'

assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'ubuntu-' 'CI runs on Ubuntu'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'macos-' 'CI runs on macOS'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'bash tests/run.sh' 'CI runs the portable contract suite'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'shellcheck' 'CI installs and runs ShellCheck on Ubuntu'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'actions/checkout@[0-9a-f]{40}' 'CI pins checkout to a reviewed commit'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'persist-credentials:[[:space:]]*false' 'CI does not persist checkout credentials'

finish_tests
