#!/usr/bin/env bash
set -u
. "$(dirname "$0")/testlib.sh"

method="$REPO_DIR/shared/method.md"
claude="$REPO_DIR/claude/SKILL.md"
codex="$REPO_DIR/codex/SKILL.md"
template="$REPO_DIR/assets/goal.md.tmpl"
readme="$REPO_DIR/README.md"
codex_metadata="$REPO_DIR/codex/agents/openai.yaml"

assert_file_contains "$method" 'Triage|TRIAGE' 'canonical shared method documents triage'
assert_file_contains "$method" 'investigat' 'canonical shared method documents investigation'
assert_file_contains "$method" 'MUST-ASK|DERIVE' 'canonical shared method documents fact classification'
assert_file_contains "$method" 'gate' 'canonical shared method documents gates'
assert_file_contains "$method" 'chain' 'canonical shared method documents chaining'
assert_file_contains "$method" 'autonom' 'canonical shared method documents autonomy'
assert_file_contains "$method" 'success.*failure.*iteration.*cost.*wall-clock|success.*failure.*iterations.*cost.*wall-clock' 'canonical method requires complete stop rules'
assert_file_contains "$method" 'out-of-repository path alone is not protection|out-of-repository.*alone.*not' 'canonical method conditions gate-state resistance on sandbox permissions'
assert_file_contains "$method" 'GATE_SURFACE' 'canonical method requires explicit GATE_SURFACE configuration'
assert_file_contains "$method" 'whitespace-separated.*glob/list|glob/list.*whitespace-separated' 'canonical method documents GATE_SURFACE list semantics'
assert_file_contains "$method" 'repository root' 'canonical method documents repository-relative surface resolution'
assert_file_contains "$method" 'regular file' 'canonical method requires regular-file surface entries'
assert_file_contains "$method" 'surface digest detects only changes' 'canonical method limits digest protection to post-baseline changes'
assert_file_contains "$method" 'after its first trusted baseline' 'canonical method requires a trusted digest baseline'
assert_file_contains "$method" 'prime it before maker edits|read-only.*maker|pre-record.*baseline' 'canonical method requires protected or pre-established surface baseline'
assert_file_contains "$claude" 'shared/method.md' 'Claude adapter mandates the canonical shared method'
assert_file_contains "$codex" 'shared/method.md' 'Codex adapter mandates the canonical shared method'
assert_file_contains "$claude" '4,?000' 'Claude adapter documents the official 4,000-character condition limit'
assert_file_contains "$claude" 'stop_hook_active' 'Claude adapter documents stop_hook_active'
assert_file_contains "$claude" 'eight consecutive|8 consecutive' 'Claude adapter documents the eight-consecutive-block limit'
assert_file_contains "$claude" 'By default.*eight consecutive blocks without progress|By default.*8 consecutive blocks without progress' 'Claude adapter states the default no-progress block condition'
assert_file_contains "$claude" 'CLAUDE_CODE_STOP_HOOK_BLOCK_CAP' 'Claude adapter names the platform block-cap override'
assert_file_contains "$claude" 'GOAL_GATE_CAP.*<= 8|GOAL_GATE_CAP.*at least the chosen repository cap' 'Claude adapter keeps repository and platform caps compatible'
assert_file_contains "$codex" 'PreToolUse' 'Codex adapter documents PreToolUse coverage'
assert_file_contains "$codex" 'Bash' 'Codex adapter names Bash PreToolUse coverage'
assert_file_contains "$codex" 'apply_patch' 'Codex adapter names apply_patch PreToolUse coverage'
assert_file_contains "$codex" 'validates only.*Bash' 'Codex adapter explicitly bounds validated PreToolUse coverage'
assert_file_contains "$codex" 'do not infer coverage.*other tool.*payload shape' 'Codex adapter disclaims unvalidated tools and payloads'
assert_not_contains "$(cat "$codex")" 'MCP|Hosted tools|write_stdin' 'Codex adapter makes no stale broad coverage claim'
assert_file_contains "$claude" 'https://code.claude.com/docs/' 'Claude platform facts cite official documentation'
assert_file_contains "$codex" 'https://learn.chatgpt.com/docs/hooks' 'Codex platform facts cite official documentation'
assert_not_contains "$(cat "$codex")" '/goal' 'Codex adapter makes no unsupported /goal claim'
assert_not_contains "$(cat "$codex_metadata")" '/goal' 'Codex UI metadata makes no unsupported /goal claim'
assert_not_contains "$(cat "$REPO_DIR/shared/autonomy.md")" 'Codex caveat:.*shell only|PreToolUse.*intercepts.*shell only' 'shared autonomy policy has no stale Codex shell-only claim'
shared_policy="$(cat "$REPO_DIR"/shared/*.md)"
assert_not_contains "$shared_policy" '`/goal|claude -p|codex exec|--dangerously-skip-permissions|CLAUDE_CODE_|stop_hook_active|#47810|transcript-only|transcript evaluator|Claude Code' 'shared policy contains no known platform-specific invocation or mechanics'

assert_file_contains "$template" 'stop_rules:' 'persisted sub-goal template has stop_rules'
assert_file_contains "$template" 'success' 'persisted sub-goal template has a success stop rule'
assert_file_contains "$template" 'failure' 'persisted sub-goal template has a failure stop rule'
assert_file_contains "$template" 'iteration' 'persisted sub-goal template has an iteration stop rule'
assert_file_contains "$template" 'cost' 'persisted sub-goal template has a cost stop rule'
assert_file_contains "$template" 'wall.?clock|time' 'persisted sub-goal template has a wall-clock stop rule'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'Class 3' 'autonomy policy names Class 3 actions'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'explicit.*bounded.*human|human.*bounded.*authori' 'Class 3 external or spending actions require bounded human authority'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'Class 4' 'autonomy policy names Class 4 actions'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'unattended' 'Class 4 policy is scoped to unattended execution'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'any `push`' 'Class 4 policy denies every unattended git push'
assert_file_contains "$REPO_DIR/shared/autonomy.md" 'commit.*authori|authori.*commit' 'commits require user or repository authority'
assert_file_contains "$REPO_DIR/shared/chaining.md" 'insufficient' 'disjoint artifacts are explicitly insufficient for parallelism'

for gate in "$REPO_DIR/assets/gate.claude.sh" "$REPO_DIR/assets/gate.codex.sh"; do
  assert_not_contains "$(cat "$gate")" 'GATE_CMD:-pytest' 'gate has no stale implicit pytest command default'
  assert_file_contains "$gate" 'GATE_CMD' 'gate names explicit GATE_CMD configuration'
  assert_file_contains "$gate" 'GOAL_GATE_CAP' 'gate names explicit GOAL_GATE_CAP configuration'
done
assert_file_contains "$REPO_DIR/shared/gates.md" 'GATE_SURFACE' 'gate guide names mandatory GATE_SURFACE configuration'
assert_file_contains "$REPO_DIR/shared/gates.md" 'ordinary shell word splitting.*glob expansion|shell glob/list' 'gate guide documents exact surface expansion semantics'
assert_file_contains "$REPO_DIR/shared/gates.md" 'trusted baseline' 'gate guide warns that surface hashing needs a trusted baseline'
assert_file_contains "$REPO_DIR/shared/gates.md" 'read-only.*before' 'gate guide requires a protected surface before maker work'
assert_file_contains "$REPO_DIR/shared/gates.md" 'same session payload|same session-keyed state' 'gate guide limits trusted priming to the actual session key'
assert_file_contains "$REPO_DIR/shared/gates.md" '[Mm]anual or pre-session priming is not' 'gate guide rejects unreliable out-of-session priming'
assert_file_contains "$REPO_DIR/shared/gates.md" '[Rr]equired for every unattended permission mode' 'gate guide requires lifecycle verification for unattended execution'

assert_file_contains "$readme" 'finish line.*prove|bounded goal contract' 'README leads with a concrete outcome'
assert_file_contains "$readme" 'platform-neutral.*Claude Code.*Codex|Claude Code.*Codex.*platform-neutral' 'README accurately bounds platform support'
assert_not_contains "$(cat "$readme")" 'safe unattended execution' 'README does not make an absolute unattended-safety claim'
assert_file_contains "$readme" '^```mermaid' 'README includes a GitHub-native workflow diagram'
assert_file_contains "$readme" '## Quick start' 'README provides a first-use path'
assert_file_contains "$readme" '## Worked example' 'README demonstrates a bounded goal contract'
assert_file_contains "$readme" '## When to use it' 'README explains when the method is appropriate'
assert_file_contains "$readme" 'not a security boundary|not containment' 'README states the hook safety boundary'
assert_file_contains "$readme" '\[Quick start\]\(docs/quickstart\.md\)' 'README links the detailed quick start'
assert_file_contains "$readme" '\[Examples\]\(docs/examples\.md\)' 'README links checked examples'
assert_file_contains "$readme" '\[Security model\]\(docs/security-model\.md\)' 'README links the security model'
assert_file_contains "$readme" 'scripts/build-bundles\.sh' 'README documents bundle construction'
assert_file_contains "$readme" 'install\.sh' 'README documents bundle-local copy installation'
assert_file_contains "$readme" 'refresh-local\.sh.*--install' 'README documents the explicit local refresh command'
assert_file_contains "$readme" 'refuses an occupied target|force-overwrite' 'README documents collision refusal without overwrite'
assert_file_contains "$readme" 'jq' 'README documents jq prerequisite'
assert_file_contains "$readme" 'GATE_CMD' 'README documents trusted GATE_CMD'
assert_file_contains "$readme" 'GOAL_GATE_CAP' 'README documents explicit gate cap'
assert_file_contains "$readme" 'GATE_SURFACE' 'README documents mandatory gate surface'
assert_file_contains "$readme" 'trusted baseline' 'README explains the trusted surface baseline'
assert_file_contains "$readme" 'read-only.*before' 'README gives an operationally safe surface setup'
assert_file_contains "$readme" 'same session payload.*state key' 'README explains the session-keyed priming constraint'
assert_file_contains "$readme" 'manual or pre-session.*not reliable' 'README rejects unreliable priming guidance'
assert_file_contains "$readme" 'decision.*block' 'README documents retry hook output'
assert_file_contains "$readme" 'continue.*false|needs-human|needs human' 'README documents terminal gate output'
assert_file_contains "$readme" '\.claude/settings\.json' 'README shows Claude hook registration'
assert_file_contains "$readme" '\.codex/hooks\.json' 'README shows Codex hook registration'
assert_file_contains "$readme" 'bash tests/run.sh' 'README names the contract test command'
assert_file_contains "$readme" 'out of scope' 'README says an external driver is out of scope'

assert_file_contains "$REPO_DIR/docs/quickstart.md" '## Install|## Choose' 'quick start documents installation'
assert_file_contains "$REPO_DIR/docs/quickstart.md" 'refresh-local\.sh.*--install' 'quick start documents the explicit local refresh command'
assert_file_contains "$REPO_DIR/docs/quickstart.md" '/writing-goals' 'quick start documents Claude invocation'
assert_file_contains "$REPO_DIR/docs/quickstart.md" '\$writing-goals' 'quick start documents Codex invocation'
assert_file_contains "$REPO_DIR/docs/examples.md" 'Done when:|Done when ' 'examples include a completion contract'
assert_file_contains "$REPO_DIR/docs/examples.md" 'raw output|exit code' 'examples require reproducible evidence'
assert_file_contains "$REPO_DIR/docs/security-model.md" 'OS-level sandbox' 'security model names the real unattended boundary'
assert_file_contains "$REPO_DIR/docs/security-model.md" 'threat|Threat' 'security model documents threats'

assert_file_contains "$REPO_DIR/LICENSE" '^MIT License$' 'repository has the standard MIT license'
assert_file_contains "$REPO_DIR/LICENSE" 'Copyright \(c\) 2026 iliaim' 'MIT license identifies the public copyright holder'
assert_file_contains "$REPO_DIR/SECURITY.md" 'private vulnerability reporting|privately' 'security policy provides a private reporting route'
assert_file_contains "$REPO_DIR/SECURITY.md" 'supported|Supported' 'security policy explains supported versions'
assert_file_contains "$REPO_DIR/CONTRIBUTING.md" 'bash tests/run\.sh' 'contributing guide gives the exact verification command'
assert_file_contains "$REPO_DIR/CONTRIBUTING.md" 'trust boundary|security' 'contributing guide calls out safety-sensitive changes'
assert_file_contains "$REPO_DIR/CONTRIBUTING.md" 'install\.sh.*scripts/build-bundles\.sh' 'contributing guide checks current installer scripts'
assert_not_contains "$(cat "$REPO_DIR/CONTRIBUTING.md")" 'sync\.sh' 'contributing guide has no retired sync installer reference'
assert_file_contains "$REPO_DIR/SUPPORT.md" 'issue|Issue' 'support policy names the support channel'
assert_file_contains "$REPO_DIR/CODE_OF_CONDUCT.md" 'Our Standards' 'repository has enforceable conduct standards'
assert_file_contains "$REPO_DIR/CHANGELOG.md" '## \[Unreleased\]' 'changelog has an Unreleased section'
assert_file_contains "$REPO_DIR/.github/PULL_REQUEST_TEMPLATE.md" 'bash tests/run\.sh' 'pull request template requires exact verification'
assert_file_contains "$REPO_DIR/.github/PULL_REQUEST_TEMPLATE.md" 'trust boundary|Security' 'pull request template asks about security impact'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/1-documentation.yml" '^name:' 'documentation issue form is discoverable'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/2-bug.yml" '^name:' 'bug issue form is discoverable'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/2-bug.yml" 'bundle/copy installer' 'bug form names the current installer'
assert_not_contains "$(cat "$REPO_DIR/.github/ISSUE_TEMPLATE/2-bug.yml")" 'sync\.sh' 'bug form has no retired sync installer reference'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/3-compatibility.yml" '^name:' 'compatibility issue form is discoverable'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/4-feature-proposal.yml" '^name:.*[Ff]eature proposal' 'feature proposal issue form is discoverable'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/config.yml" 'blank_issues_enabled: false' 'issue chooser directs reporters to structured forms'
assert_path_absent "$REPO_DIR/.github/ISSUE_TEMPLATE/5-public-moderation.yml" 'repository does not expose a public conduct-report form'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/config.yml" 'reporting-abuse-or-spam' 'issue chooser routes private GitHub abuse to GitHub Support'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/4-feature-proposal.yml" 'security/advisories/new' 'feature form routes vulnerabilities to private vulnerability reporting'
assert_file_contains "$REPO_DIR/.github/ISSUE_TEMPLATE/4-feature-proposal.yml" 'reporting-abuse-or-spam' 'feature form routes private GitHub abuse to GitHub Support'
assert_not_contains "$(cat "$REPO_DIR/.github/ISSUE_TEMPLATE/4-feature-proposal.yml")" 'private conduct reports' 'feature form makes no nonexistent private conduct-route claim'
assert_file_contains "$REPO_DIR/CODE_OF_CONDUCT.md" 'separate private conduct-reporting inbox' 'conduct policy states the private-inbox limitation'
assert_file_contains "$REPO_DIR/CODE_OF_CONDUCT.md" 'reporting-abuse-or-spam' 'conduct policy routes private GitHub abuse to GitHub Support'
assert_file_contains "$REPO_DIR/CODE_OF_CONDUCT.md" 'reserved for security vulnerabilities' 'conduct policy reserves private vulnerability reporting for security'
assert_file_contains "$REPO_DIR/CODE_OF_CONDUCT.md" 'times are not guaranteed' 'conduct policy does not promise unavailable response timing'
assert_not_contains "$(cat "$REPO_DIR/CODE_OF_CONDUCT.md")" 'may be raised through|reviewed promptly' 'conduct policy makes no public-form or prompt-response promise'
assert_file_contains "$REPO_DIR/SUPPORT.md" 'security/advisories/new' 'support policy links the private vulnerability route'
assert_file_contains "$REPO_DIR/SUPPORT.md" 'reporting-abuse-or-spam' 'support policy links the private GitHub abuse route'
assert_file_contains "$readme" 'reporting-abuse-or-spam' 'README routes private GitHub abuse separately'
assert_file_contains "$readme" 'security/advisories/new' 'README routes security vulnerabilities separately'
assert_file_contains "$REPO_DIR/PLAN.md" 'as-built|As-built' 'PLAN is an as-built record'
assert_file_contains "$REPO_DIR/PLAN.md" 'compatibility' 'PLAN contains a compatibility record'
assert_file_contains "$REPO_DIR/PLAN.md" 'Bundle-local `install\.sh all`|Symlink-free copy tree' 'PLAN records bundle copy installation'
assert_not_contains "$(cat "$REPO_DIR/PLAN.md")" 'sync\.sh' 'PLAN has no retired sync installer reference'
assert_not_contains "$(cat "$REPO_DIR/PLAN.md")" 'Live symlinks|live symlink' 'PLAN has no live-link installation semantics'
assert_not_contains "$(cat "$REPO_DIR/PLAN.md")" '`--force`' 'PLAN has no force-overwrite installation semantics'
assert_not_contains "$(cat "$REPO_DIR/PLAN.md")" 'Status:.*draft|Ready for your review before build' 'PLAN does not describe the implemented system as a draft'

assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'ubuntu-' 'CI runs on Ubuntu'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'macos-' 'CI runs on macOS'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'bash tests/run.sh' 'CI runs the portable contract suite'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'shellcheck' 'CI installs and runs ShellCheck on Ubuntu'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'actions/checkout@[0-9a-f]{40}' 'CI pins checkout to a reviewed commit'
assert_file_contains "$REPO_DIR/.github/workflows/ci.yml" 'persist-credentials:[[:space:]]*false' 'CI does not persist checkout credentials'

# G12 public-integration contract.  These are intentionally separate from the
# earlier documentation checks: G12 is the point at which the public reader
# journey must describe the already-canonical v1 workflow without restating it.
assert_file_contains "$readme" '\[Workflow contract\]\(shared/workflow\.md\)' 'G12_WORKFLOW_DOCS: README links the canonical workflow contract'
assert_file_contains "$readme" 'checkpoint-then-continue|checkpoint then continue' 'G12_WORKFLOW_DOCS: README explains checkpoint-then-continue'
assert_file_contains "$readme" 'automatic local commits' 'G12_POST_G13_EXTERNAL_GATE: README states the automatic local-commit boundary'
assert_file_contains "$readme" 'post-G13|after terminal G13' 'G12_POST_G13_EXTERNAL_GATE: README identifies the one post-G13 gate'
assert_file_contains "$readme" 'human external.*gate|external.*human.*gate' 'G12_POST_G13_EXTERNAL_GATE: README reserves external action for the human gate'
assert_file_contains "$REPO_DIR/shared/publication.md" 'Approved execution may create commits automatically' 'G12_POST_G13_EXTERNAL_GATE: canonical publication policy permits automatic local commits'
assert_file_contains "$REPO_DIR/shared/publication.md" 'One final human gate.*only after terminal G13' 'G12_POST_G13_EXTERNAL_GATE: canonical publication policy has one final external gate'
assert_file_contains "$REPO_DIR/docs/security-model.md" 'OS-level sandbox' 'G12_SECURITY_CLAIMS: security guide names the actual containment boundary'
assert_file_contains "$readme" '\[Security model\]\(docs/security-model\.md\)' 'G12_SECURITY_CLAIMS: README links the security model'
assert_file_contains "$readme" 'all v1 state remains local' 'G12_LOCAL_ONLY_NO_EXPORT_OR_RESTORE: README states the local-only durability boundary'
assert_file_contains "$readme" 'single-machine risk' 'G12_FAILURE_DOMAIN_LIMITS: README records the accepted failure domain'
assert_not_contains "$(cat "$readme" "$REPO_DIR/docs"/*.md)" 'cross-host recovery|remote target|remote backup' 'G12_LOCAL_ONLY_NO_EXPORT_OR_RESTORE: public guides make no remote durability claim'
assert_file_contains "$REPO_DIR/CONTEXT.md" 'immutable Goal definitions' 'G12_GOAL_LEDGER_DOMAIN: Goal Ledger includes immutable Goal definitions'
assert_file_contains "$REPO_DIR/CONTEXT.md" 'protected lifecycle records' 'G12_GOAL_LEDGER_DOMAIN: Goal Ledger includes protected lifecycle records'
assert_file_contains "$REPO_DIR/CONTEXT.md" 'local plan/evidence.*untrusted|local plan and evidence.*untrusted' 'G12_GOAL_LEDGER_DOMAIN: local plan and evidence are untrusted'
assert_file_contains "$readme" 'GitHub Issues.*future.*non-authoritative|future.*non-authoritative.*GitHub Issues' 'G12_GITHUB_PROJECTION_FUTURE_ONLY: GitHub collaboration is future and non-authoritative'
assert_not_contains "$(cat "$readme" "$REPO_DIR/docs"/*.md "$REPO_DIR/.github/PULL_REQUEST_TEMPLATE.md")" 'tracker (module|goal|bot|webhook|reverse sync|adapter)' 'G12_NO_TRACKER_SEAM: public surfaces expose no tracker seam'
assert_file_contains "$REPO_DIR/shared/workflow.md" 'host owns activation and continuation' 'G12_HOST_NATIVE_SEQUENTIAL_SINGLE_MODEL: host owns sequential activation'
assert_file_contains "$REPO_DIR/shared/workflow.md" 'parallel-dispatch request fails closed' 'G12_HOST_NATIVE_SEQUENTIAL_SINGLE_MODEL: parallel dispatch is rejected'
assert_not_contains "$(cat "$codex")" 'external goal-chain driver' 'G12_HOST_NATIVE_SEQUENTIAL_SINGLE_MODEL: Codex skill makes no external-driver claim'
assert_file_contains "$codex" 'host-native continuation|host native continuation' 'G12_HOST_NATIVE_SEQUENTIAL_SINGLE_MODEL: Codex skill declares host-native continuation'
assert_file_contains "$codex" 'non-interactive entrypoint' 'G12_HOST_NATIVE_SEQUENTIAL_SINGLE_MODEL: Codex skill retains its non-interactive boundary'
assert_file_contains "$REPO_DIR/shared/workflow.md" 'leaves the parent in progress until every ordered slice is complete' 'G12_PARENT_CHILD_COMPLETION_DOCS: only all slices complete the parent'
assert_file_contains "$REPO_DIR/shared/workflow.md" 'background continuation, or advance the parent' 'G12_PARENT_CHILD_COMPLETION_DOCS: a checker cannot advance the parent'

# The protected-red receipt needs a stable, goal-specific failure line rather
# than a generic assertion summary.  Keep it immediately before finish_tests
# so the normal assertion output remains useful to the maker.
if [ "$TEST_FAILURES" -ne 0 ]; then
  printf '%s\n' 'FAIL: G12_PUBLIC_DOCS_MISSING' >&2
fi

finish_tests
